# Load ConflictWiki Data

In [2]:
import os, itertools
import pandas as pd

### Load Data

In [3]:
ROOT = os.path.abspath(os.getcwd())

map_path = ROOT + "/conflict_entity_map.json"
entity_path = ROOT + "/entity.json"
conflict_path = ROOT + "/conflict.json"

map_df = pd.read_json(map_path, lines=True)
entity_df = pd.read_json(entity_path, lines=True)
conflict_df = pd.read_json(conflict_path, lines=True)

print(f"n conflicts: {len(conflict_df)}, n entities: {len(entity_df)}")

n conflicts: 1145, n entities: 1199

### Search for any mention of Mali in the Conflicts

In [4]:
# Define a search function
def search_string(s, search):
    return search in str(s).lower()

# Search for the string 'al' in all columns
mask = conflict_df.apply(lambda x: x.map(lambda s: search_string(s, 'usa')))

# Filter the DataFrame based on the mask
filtered_df = conflict_df.loc[mask.any(axis=1)]
filtered_df

,conflict_id,conflict_name,url,n_belligerents,n_entities,place,date,date_start,date_end,status,casualties,casualties_num,casualties_sum,strength,strength_num,strength_sum,commander,result
2,201936,2003 invasion of Iraq,https://en.wikipedia.org/wiki/2003_invasion_of...,2,17,Iraq,20 March - 1 May 2003,2021-03-20,2003-05-01,None,{'0': 'Coalition: 214 killed606 wounded (U.S.)...,"{'0': [214.0, 606.0, 24.0, 238.0, 1000.0], '1'...","{'0': 2082.0, '1': 172996.0, '2': 14769.0}","{'0': ': 192,000 personnel: 45,000 troops : 2,...","{'0': [192000.0, 45000.0, 2000.0, 194.0, 70000...","{'0': 619628.0, '1': 4015761.0}","{'0': ['Babaker Shawkat B. Zebari', 'Iraqi Kur...",Coalition operational success. Ba'athist Iraq ...
3,207031,Battle of Baghdad (2003),https://en.wikipedia.org/wiki/Battle_of_Baghda...,2,3,"Baghdad, Ba'athist Iraq",3-12 April 2003,2003-04-03,2003-04-12,None,"{'0': '1,700–2,120 killed (independent estimat...","{'0': [1700.0, 2120.0, 2320.0], '1': [34.0, 1....","{'0': 6140.0, '1': 54.0}","{'0': '45,000', '1': '30,000'}","{'0': [45000.0], '1': [30000.0]}","{'0': 45000.0, '1': 30000.0}","{'0': ['Saddam Hussein', 'Sayf al-Din al-Rawi'...",Decisive Coalition victory. Fall of Ba'ath Par...
4,312905,Lebanese Civil War,https://en.wikipedia.org/wiki/Lebanese_Civil_War,4,28,Lebanon,13 April 1975 - 13 October 1990 Battle of Sido...,1975-04-13,1990-10-13,None,{},{},{},"{'0': '', '1': '', '2': ' 25,000 troops (1976)...","{'2': [25000.0, 1976.0], '3': [1200.0, 1000.0,...","{'2': 26976.0, '3': 4600.0}","{'0': ['Antoine Lahad', 'Etienne Saqr', 'Menac...",Taif Agreement Christian 55:45 ascendancy repl...
16,1138374,Second Battle of Fallujah,https://en.wikipedia.org/wiki/Second_Battle_of...,2,9,"Fallujah, Iraq",7 November - 23 December 2004,2021-11-07,2004-12-23,None,{'0': ' 95 killed 4 killedTotal: 107–110 kille...,"{'0': [95.0, 4.0, 107.0, 110.0, 613.0], '1': [...","{'0': 929.0, '1': 4200.0, '2': 2051.0}","{'0': ' 10,500 troops 2,000 Iraqi security fo...","{'0': [10500.0, 2000.0, 850.0, 13350.0], '1': ...","{'0': 26700.0, '1': 7700.0}","{'0': ['Keith Stalder', 'Richard F. Natonski',...",Coalition victory
26,1606497,Casamance conflict,https://en.wikipedia.org/wiki/Casamance_conflict,2,6,"Casamance, Senegal",1982 - 1 May 2014 main conflic2015 - present l...,1982-07-05,2014-05-01,Unilateral ceasefire; ongoing low-level violence.,"{'0': '', '1': '', '2': '5,000 killed in total...","{'2': [5000.0, 1982.0, 60000.0]}",{'2': 66982.0},{'0': ' Armed Forces of Senegal: Thousands (20...,"{'0': [2012.0], '1': [180.0, 2006.0]}","{'0': 2012.0, '1': 2186.0}","{'0': ['Senegal', 'Abdou Diouf', 'Macky Sall',...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,61341822,2019–2021 Persian Gulf crisis,https://en.wikipedia.org/wiki/2019–2021_Persia...,2,6,,5 May 2019 - present,2019-05-05,2021-07-05,{{Collapsible list titlestyle,{'0': '{{Collapsible list titlestyle title tit...,"{'0': [2.0], '1': [3.0]}","{'0': 2.0, '1': 3.0}","{'0': '{{Collapsible list titlestyle title 50,...","{'0': [50000.0], '1': [1.0]}","{'0': 50000.0, '1': 1.0}","{'0': ['Mohammed bin Salman', 'Linda Reynolds'...",None
1069,61913712,Operation Victory from God,https://en.wikipedia.org/wiki/Operation_Victor...,2,5,Saudi Arabia-Yemen border; Yemen-Saudi Arabia ...,25 August - late September 2019,2021-08-25,2019-09-01,,"{'0': 'unknown', '1': 'According to the Houthi...","{'1': [500.0, 2000.0, 15.0]}",{'1': 2515.0},"{'0': 'Several infantry, armored, and missile ...",{'1': [3.0]},{'1': 3.0},"{'0': [], '1': []}",Houthi victory
1080,62639473,Timeline of the American-led intervention in t...,https://en.wikipedia.org/wiki/Timeline_of_the_...,3,23,Syria,22 September 2014 - present,2014-09-22,2021-07-05,None,{'0': ' United States:8 servicemen killed (5 n...,"{'0': [8.0, 5.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0,...","{'0': 24.0, '1': 9520.0, '2': 406.0, '3': 4297...",{'0': 'Coalition forces: Coalition forces-air ...,"{'1': [100000.0, 3.0, 2.0, 31000.0, 2017.0, 7....","{'1': 193197.0, '2': 180000.0}","{'0': ['Bahrain', 'Germany', 'Khalifa bin Zaye...","Ongoing operations. 19,786 U.S. and allied air..."
1120,65548110,December 2007 Turkish incursion into northern ...,https://en.wikipedia.org/wiki/December_2007_Tu...,2,2,northern Iraq,"December 16, 2007 - December 26, 2007",2007-12-16,2007-12-26,None,"{'0': 'None', '1': '200 killed, thousands woun...","{'1': [200.0], '2': [1800.0, 10.0, 1.0]}","{'1': 200.0, '2': 1811.0}","{'0': '52 war planes', '1': '2.320-2.640 soldi...","{'0': [52.0], '1': [2320.0]}","{'0': 52.0, '1': 2320.0}","{'0': [], '1': []}",Turkish victory
1144,66567999,Battle of Hawija,https://een.wikipedia.org/wiki/Battle_of_Hawija,2,4,Eastern Iraq,20 September 2017,2017-09-20,2017-10-08,,"{'0': 'unknown', '1': '942 killed'}","{'0': 0, '1': 942}",{},{},"{'0': [42000], '1': [2000]}",{},"{'0': ['Abdul-Amir Rashid Yarallah', 'Qais Kha...",Decisive Iraqi victory

### Search for any mention of Mali in the Entities

In [5]:
def search_string(s, search):
    return search in str(s).lower()
mask = entity_df.apply(lambda x: x.map(lambda s: search_string(s, 'usa')))
filtered_df = entity_df.loc[mask.any(axis=1)]
filtered_df

,entity_id,entity_name,url,iso,language,ideology,religion
228,184764,The Jerusalem Post,https://en.wikipedia.org/wiki/The_Jerusalem_Post,[],"[French, English language, French language, En...",[],[]
367,21373,Niger,https://en.wikipedia.org/wiki/Niger,XO,"[French, French language, National language, S...",[],[]
443,37278116,Mujahideen Shura Council in the Environs of Je...,https://en.wikipedia.org/wiki/Mujahideen_Shura...,[],[],[],[]
533,21383,Nigeria,https://en.wikipedia.org/wiki/Nigeria,NG,"[English language, English, National languages...",[],[]
1010,41487145,Organization for the Islamic Revolution in the...,https://en.wikipedia.org/wiki/Organization_for...,[],[],"[Religious nationalism, Conservatism, Mohammad...",[Shia Islam]
1101,402587,Husayn ibn Ali,https://en.wikipedia.org/wiki/Husayn_ibn_Ali,[],[],[],[]
1124,56694430,Al-Ashtar Brigades,https://en.wikipedia.org/wiki/Al-Ashtar_Brigades,[],[],"[Mohammad al-Husayni al-Shirazi, Shirazi]",[]

### Look into a specific conflict (Mali War) <br>
https://en.wikipedia.org/wiki/Mali_War

In [6]:
conflict_id = 36856978 
conflict_df[conflict_df.conflict_id == conflict_id]

,conflict_id,conflict_name,url,n_belligerents,n_entities,place,date,date_start,date_end,status,casualties,casualties_num,casualties_sum,strength,strength_num,strength_sum,commander,result
482,36856978,Mali War,https://en.wikipedia.org/wiki/Mali_War,3,17,Northern Mali,8 March 2004 ; access-date=28 January 2013}} ...,2004-03-08,2013-01-01,None,"{'0': ' 181+ killed, 400 captured Total:1,000–...","{'0': [181.0, 400.0, 1000.0, 1500.0, 417.0, 10...","{'0': 3725.0, '1': 2180.0, '2': 1940.0}","{'0': ' 6,000–7,000(pre-war: ~12,150) 3,000 ...","{'0': [6000.0, 7000.0, 12150.0, 3000.0, 2000.0...","{'0': 64075.0, '1': 3000.0, '2': 4200.0}","{'0': ['Brigade General', 'Dioncounda Traor', ...",List of ongoing military conflicts The Tuareg ...

In [7]:
belligerent_groups = map_df[map_df.conflict_id == conflict_id]['entity_ids'].to_list()[0]
involved_entities = list(itertools.chain.from_iterable(belligerent_groups))

for i, entities in enumerate(belligerent_groups):
    entity_list = entity_df[entity_df['entity_id'].isin(entities)].entity_name.to_list()
    print(f'belligerents {i}: {entity_list}')

belligerents 0: ['France', 'Mali', 'Malian Armed Forces', 'Economic Community of West African States']
belligerents 1: ['National Movement for the Liberation of Azawad']
belligerents 2: ['Al-Qaeda', 'Ansar al-Sharia', 'Islamic State in the Greater Sahara', 'Al-Qaeda in the Islamic Maghreb', "Jama'at Nasr al-Islam wal Muslimin", 'Movement for Oneness and Jihad in West Africa', 'Boko Haram', 'Ansar Dine', 'Al-Mourabitoun', 'Ansaru', 'Macina Liberation Front']